#!/usr/bin/env python3
'''-------'''
from sys import argv
from math import sqrt


def open_file(file_name):
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    factor_no = []
    for line in lines:
        factor_no.append(int(line))
    return factor_no

def times(n):
    for i in range(1, n):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break

def fact_list(l):
    for i in l:
        times(i)

if len(argv) == 2:
    fact_list(open_file(argv[1]))
